### ISSUE TITLE
Partie2 V1 - Client lourd bornes de réservation

### ISSUE THREAD

**Issue by Wiiz83** [Wiiz83/ProjetSpacelib#10]
Des	 bornes	 de	 réservation	 présentes dans	 les	 stations	 pour	 permettre	 aux	 usagers	 de	réserver	 une	 navette	 et	réaliser	 leur voyage.	 Ces	 bornes	 seront	 des	clients	 lourds du	système	central

**Comment by mh0** [comment]
Il reste les tests.
