### ISSUE TITLE
Début voyage / transfert : supprimer l'ID de la navette sur le quai 

### ISSUE THREAD

**Issue by mh0** [Wiiz83/ProjetSpacelib#21]

**Comment by Wiiz83** [comment]
Quand un usager utilise la borne et veut emprunter une navette, on vérifie qu'il y a pas une réservation prévue avec les mêmes attributs que celles saisies : dans ce cas, c'est une résa planifiée (précédemment effectuée dans le client web usager).

![image](https://user-images.githubusercontent.com/10958435/41196148-6aff8ebc-6c3a-11e8-91ac-f39d399f49ae.png)
