### ISSUE TITLE
Réservation d'un voyage

### ISSUE THREAD

**Issue by Khwaj7** [Wiiz83/ProjetSpacelib#30]
Deux voyages pour la même date, même quai d'arrivée.
SPECS : Il ne doit y avoir qu'une seule réservation possible pour un utilisateur, sur un créneau donné.

![image](https://user-images.githubusercontent.com/7382894/41189197-368fb3d4-6bca-11e8-8373-9df3e149d9db.png)

**Comment by Wiiz83** [comment]
Correction réalisée 

![image](https://user-images.githubusercontent.com/10958435/41195686-c3336b60-6c32-11e8-845b-1621817b7718.png)

![image](https://user-images.githubusercontent.com/10958435/41195692-d44c6b90-6c32-11e8-82f3-432fc938df2e.png)

A tester
