### ISSUE TITLE
Réservation : check si quai disponible à l'arrivée 

### ISSUE THREAD

**Issue by Wiiz83** [Wiiz83/ProjetSpacelib#31]
Si deux réservations effectuées et arrivant au même quai : 
- pas possible sinon le jour j collisions au quai d'arrivée

**Comment by Wiiz83** [comment]
@FarahonKhwaja à tester avec deux usagers différents

**Comment by Khwaj7** [comment]
Voyage réservé sur **USAGERP** : 
![image](https://user-images.githubusercontent.com/7382894/41196132-fab94bac-6c39-11e8-9b73-908a422a8e06.png)


Voyage réservé sur **USAGERL** : 
![image](https://user-images.githubusercontent.com/7382894/41196128-e231cbc2-6c39-11e8-99c1-9fdf1d2413cd.png)

Deux voyages, prévus à la même date par deux voyageurs différents. Ils arriveront au même quai.

**Comment by Wiiz83** [comment]
Non géré :'(
