### ISSUE TITLE
Client Admin Lourd - Crash au moment de saisir les distances d'une nouvelle station

### ISSUE THREAD

**Issue by Khwaj7** [Wiiz83/ProjetSpacelib#33]
J'ai créé une première station.
Quand j'en crée une deuxième et que j'arrive au moment d'indiquer la distance de cette station à l'autre station que j'ai créé, l'appli crash. Ci-joint la stack.
[stacktrace_crash_appli_admin_spacelib.txt](https://github.com/Wiiz83/ProjetSpacelib/files/2087346/stacktrace_crash_appli_admin_spacelib.txt)

**Comment by Wiiz83** [comment]
@mh0 dans initialdata.sql, il faut que tous les ID commencent à 50

**Comment by Wiiz83** [comment]
problème résolu
