### ISSUE TITLE
Partie1 V1 - Client Lourd Admin Spacelib

### ISSUE THREAD

**Issue by Wiiz83** [Wiiz83/ProjetSpacelib#9]
Une	application cliente	lourde	ou	web	(au	choix) pour	l’administrateur de	Spacelib	qui	a	en	charge	la	construction	de	nouvelles	stations	spatiales	et

**Comment by mh0** [comment]
Est-ce que l'admin doit renseigner le temps de trajet entre la station ajoutée et les autres stations ?

**Comment by mh0** [comment]
Est-ce que l'admin doit renseigner un login/mdp pour accéder à l'appli ?

**Comment by Wiiz83** [comment]
Je dirais oui pour renseigner les temps de trajet, sinon on va avoir des problèmes lorsque un usager effectue une réservation.
Pour login/password, comme tu veux
